- name: Install dependency softwares
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "fish"
    - "xclip"
    - "xdotool"
    - "rxvt-unicode"
    - "screen"
    - "xsel"
    - "git"
    - "xfce4-screenshooter"
    - "feh"
